# Generated by Django 5.0.3 on 2024-03-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
