# Generated by Django 5.0.3 on 2024-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
