# Generated by Django 5.0.3 on 2024-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productimage_color_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="price_rubl",
        ),
        migrations.AddField(
            model_name="product",
            name="HaveProduct",
            field=models.BooleanField(default=False, verbose_name="В наличии"),
        ),
        migrations.AddField(
            model_name="product",
            name="price_dollar",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="product",
            name="price_som",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
