# Generated by Django 5.0.3 on 2024-05-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0010_rename_price_product_price_rubl_product_haveproduct_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_dollar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_rubl",
        ),
    ]
