# Generated by Django 5.0.3 on 2024-05-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_product_price_dollar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price_som",
            new_name="price",
        ),
    ]
