# Generated by Django 5.0.3 on 2024-03-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_caseparameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caseparameter",
            name="key",
        ),
    ]
