# Generated by Django 5.0.3 on 2024-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_location', models.CharField(default='Не указано', max_length=255, verbose_name='Местоположение компании')),
                ('social_media_links', models.JSONField(default=dict, verbose_name='Ссылки на социальные медиа')),
                ('about_us', models.TextField(default='Информация о компании', verbose_name='О нас')),
            ],
        ),
    ]
