# Generated by Django 5.0.3 on 2024-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фотография "О нас"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_image',
            field=models.ImageField(blank=True, upload_to='settings', verbose_name='Фотография местоположения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение компании'),
        ),
    ]
